# source 'https://rubygems.org'
#source 'https://ruby.taobao.org'
source 'http://gems.ruby-china.org'

ruby '2.3.1'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 4.2.6'
# active model
gem 'activemodel'
#decorator(view model)
gem 'draper'
#slim view engine
gem 'slim-rails'

# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
gem 'less-rails'
gem 'sprockets', '~>3.6.3'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'


gem 'bootstrap-sass', '~> 3.3.6' #bootstrap
gem 'bootstrap_form'

# we can use bower's jquery directly, but rails need jquery_ujs to implement model delete for model index page.
gem 'jquery-rails', '~> 4.1.0'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# Xml parser
gem 'actionpack-xml_parser'
gem 'xml-simple'

#restful client
gem 'rest-client'

# See https://github.com/rails/execjs#readme for more supported runtimes
gem 'therubyracer', platforms: :ruby

# Default values for AR models
gem "default_value_for", "~> 3.0.0"
# Use ActiveModel has_secure_password
gem 'bcrypt', '~> 3.1.7'
# track model data changes
gem 'paper_trail', '~> 5.1.0'
# log action
gem 'impressionist'

gem 'wisper'
gem 'wisper-activerecord'

# rails step-by-step wizard controller
gem 'wicked'

gem 'wechat'
gem 'wx_pay'
gem 'weui-rails'

# Generic hooks with callbacks for Ruby.
gem 'hooks'

# search and filter active record data
gem 'scoped_search'
gem 'country_select'
gem 'hashids' #hash ids

gem 'will_paginate'
gem 'will_paginate-bootstrap'

gem 'devise', '~> 3.5.2'
gem 'pundit'
gem 'rolify'
gem 'simple_captcha2', require: 'simple_captcha'

gem 'mina'
gem 'mina-sidekiq', require: false
gem 'mina-unicorn', require: false
gem 'mina-nginx', require: false
gem 'mina-multistage', require: false

gem 'factory_girl'
# factory girl
gem 'factory_girl_rails'

gem 'surveyor', :git => 'https://github.com/tengzy/surveyor.git', :ref => '2f9f7a7603907392aa1fe9ef4c15b67d9e793dfd'
gem 'GB2260'
gem 'china_city', :git => 'https://github.com/jerecui/china_city.git'
gem 'rubyXL'

# money
gem 'money'
gem 'money-rails'
gem 'currencies'

# file upload
gem 'carrierwave'
gem 'qiniu'
gem 'carrierwave-qiniu'
gem 'file_validators'
gem "rmagick"

# generate the pdf via html
gem 'wicked_pdf'

gem 'sinatra'
gem 'whenever'
gem 'sidekiq'
gem 'redis-namespace'

# ping plus plus 第三方支付
gem 'pingpp'

# Colored output to console
gem "colorize", '~> 0.7.0'

# api documentation
gem 'apipie-rails'

group :production do
  # Use Unicorn as the app server
  gem 'unicorn'

  # Use postgresql as the database for Active Record
  gem 'pg'
end

group :development do
  gem "foreman"
  gem 'brakeman', require: false
  gem 'rerun', '~> 0.11.0'
  gem 'bullet', require: false

  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'
  gem 'better_errors'
  gem 'binding_of_caller', '~> 0.7.2'
  # Docs generator
  gem "sdoc", '~> 0.4.0'
  # thin instead webrick
  gem 'thin', '~> 1.6.1'
end


group :development, :test do

  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
  gem 'awesome_print', '~> 1.2.0', require: false

  gem 'rspec-expectations'
  gem 'simplecov', :require => false
  gem 'wisper-rspec', :require => false

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'

  #sqlite
  gem 'sqlite3'

  #rspec
  gem 'rspec-rails', '~> 3.0'

  #cucumber
  gem 'cucumber-rails', :require => false
  gem 'database_cleaner'
  gem 'capybara'
  gem 'capybara-screenshot'
  gem 'capybara-webkit'
  gem 'selenium-webdriver'
  gem 'site_prism', '~> 2.9' #page model for cucumber page.
  gem 'ule_page', :git => 'https://github.com/jerecui/ule_page'
  # gem 'ule_page', :path => '/Users/tsuijy/Projects/Odde/ruby/ule_page'
  gem 'poltergeist'

  gem 'parallel_tests'

end

group :test do
  gem 'webmock'
  gem 'test_after_commit'
end
